### ISSUE TITLE
report out in metabase MSD Outcomes

### ISSUE THREAD

**Issue by hunterowens** [cal-itp/data-infra#145] opened 2021-06-08 16:38 UTC
The following outcomes are needed for tracking outcomes of the MSD program. 

[reference sheet](https://docs.google.com/spreadsheets/d/1uHqi-xbNioQBMfgVzC_-kN2B0LI-1e_a_FAWD72zhsE/edit#gid=0)

| Metric | Proposed Method |
| -------- | -------------------------- | 
| Transit Data Errors Identified | # of unique Validator errors found in the quater | 
| Transit Data Errors Resolved | # of validators errors that are not present that we are the start of the quarter | 
| Valid Schedules | # of valid schedules being scraped an put into the Data Warehouse | 
| Valid Realtime updates available in GTFS Realtime  | Number of Realtime Feeds  | 
| Alerts available in GTFS Alerts | # of agencies publishing GTFS alerts | 
| Fares available in GTFS Schedule | # of agencies publishing Fares V2 |

**Comment by hunterowens** [comment] 2021-06-08 16:38
cc @e-lo

**Comment by hunterowens** [comment] 2021-06-11 22:53
breadcrumb on Resolved errors from @mcplanner "We discussed this last time. This is meant to be a tally of errors that existed in previous months but no longer appear."

**Comment by hunterowens** [comment] 2021-06-21 17:15
First stab: #175

**Comment by mcplanner** [comment] 2021-07-21 22:52
Closed as a duplicate of #11. All ideas put into that issue.

**Closed by mcplanner** 2021-07-21 22:52 UTC
