### ISSUE TITLE
Bug: `fct_daily_rt_feed_validation_notices` exceeding available slots

### ISSUE THREAD

**Issue by themightychris** [cal-itp/data-infra#3481] opened 2024-09-27 03:14 UTC
There are [3 instances of this error to date](https://sentry.calitp.org/organizations/sentry/issues/77423/events/?referrer=issue-stream&statsPeriod=90d&stream_index=0):

<img width="1415" alt="Screenshot 2024-09-26 at 8 11 30 PM" src="https://github.com/user-attachments/assets/20bcce0d-2a49-48b4-bf44-cdd50a43db2d">

Error message:

```console
model.calitp_warehouse.fct_daily_rt_feed_validation_notices - Database Error in model fct_daily_rt_feed_validation_notices (models/mart/gtfs_quality/fct_daily_rt_feed_validation_notices.sql)
  Resources exceeded during query execution: Your project or organization exceeded the maximum disk and memory limit available for shuffle operations. Consider provisioning more slots, reducing query concurrency, or using more efficient logic in this job.
  compiled Code at target/run/calitp_warehouse/models/mart/gtfs_quality/fct_daily_rt_feed_validation_notices.sql
```

More information on this error can be found here: https://cloud.google.com/bigquery/docs/query-insights#insufficient_shuffle_quota

Essentially it appears that we have two options:

- Increase capacity for processing data—increasing costs
- Optimize the query

**Comment by themightychris** [comment] 2024-09-27 03:15
@charlie-costanzo @erikamov can you take a look at the underlying query here and see if there is any potential for optimization? Check out the docs I linked to. It might be helpful to extract the relevant query and run it from BigQuery's console to examine some of the metadata about data it is processing and reason about whether we can reduce how much data it processes through optimization

**Comment by evansiroky** [comment] 2024-10-01 21:12
I'm checking with the team on whether we need RT validation notices for all time, I'm thinking probably not.

**Comment by ohrite** [comment] 2024-10-17 21:01
The structure of the query is fairly simple:
1. Get all daily feeds (a record of retrievals per URL and day)
2. For each URL/day, create a row for each error code (there are 57)
3. For each URL/day/code, aggregate the validation runs, aggregate the warning/error messages, and calculate some metrics

After pairing with @erikamov we believe the issue is the location of the `CROSS JOIN`, and are investigating moving the cross join out to a CTE with the daily feeds table, resulting in a query that finishes at about the 50 minute mark.

After removing the join to notices, the query finishes at the 20 minute mark. Our ongoing investigation will be into speeding up the notice occurrence list aggregation.

**Comment by ohrite** [comment] 2024-10-18 21:12
During ongoing debugging with @erikamov we split the query into 4 CTEs

1. outcomes -> notices
2. daily_feeds x codes
3. daily_feed aggregate calculations per day/url
4. outcome aggregate calculations per day/url

This reduced the runtime to < 1m. We are now working on validating that the data lines up.

**Comment by erikamov** [comment] 2024-10-21 17:45
@ohrite and I rewrote the query and it is way better now. `transform_warehouse` and `transform_warehouse_full_refresh_sunday` ran succesfully!

**Comment by evansiroky** [comment] 2024-10-22 03:13
Nice work!

**Closed by evansiroky** 2024-10-22 03:13 UTC
Labels: data-pipeline-ingestion-and-modeling
