### ISSUE TITLE
Bug: odd behavior in fct_daily_rt_feed_files

### ISSUE THREAD

**Issue by owades** [cal-itp/data-infra#2192] opened 2023-01-19 21:44 UTC
**Describe the bug**
I noticed that the data quality check table `int_gtfs_quality__rt_feeds_present` started passing 100% of feeds, and started looking into it. What I found was that, beginning on 2022-11-29, no feeds have a `parse_success_file_count` value of 0. This is strange because before then, the field had a daily value that was always between 20 and 50.

I looked into the git history of `fct_daily_rt_feed_files` a bit, but didn't see a cause that was obvious to me.

**To Reproduce**
Query:
```
WITH fct_daily_rt_feed_files AS (
    SELECT * FROM `cal-itp-data-infra.mart_gtfs.fct_daily_rt_feed_files`
)

SELECT date,
       COUNT(CASE WHEN parse_success_file_count = 0 THEN 1 END) AS no_success_count,
       COUNT(*) AS feed_count
  FROM fct_daily_rt_feed_files
  WHERE date > '2022-01-01'
  GROUP BY 1
  ORDER BY 1
```
Output screenshot:
![Screen Shot 2023-01-19 at 1 41 58 PM](https://user-images.githubusercontent.com/3301353/213568339-dd53f5c6-6345-4002-9d11-c20637dd5628.png)

**Expected behavior**
I would expect at least some feeds every day to have a value greater than zero in the `parse_success_file_count` column every day, or an explanation as to why the pattern changed dramatically.

**Comment by lauriemerrell** [comment] 2023-01-19 23:39
The cause for this change is https://github.com/cal-itp/data-infra/pull/2044, which I think we only backfilled to November 28. Before that, we were considering empty files (header only) invalid and failing to parse them. That PR fixed it so we now mark those as valid from a parsing perspective. 

So, I think the change on November 28 is expected... We can possibly look into backfilling further if that would make a difference. 

But I think the actual cause here is that this check (`int_gtfs_quality__rt_feeds_present`) should probably be using a separate RT *urls* index rather than the RT *feeds* index, because using the *feeds* index is based only on feeds that had at least some files present. So it's impossible for a feed with no files to appear here.

**Comment by lauriemerrell** [comment] 2023-01-19 23:41
It looks like https://dbt-docs.calitp.org/#!/model/model.calitp_warehouse.int_gtfs_rt__daily_url_index does already exist, so I think that you may be able to handle this directly, @owades ? I would basically just swap out which index that check is using. I'll assign this to you but let me know if this doesn't make sense (or if it turns out to be more complicated than I think) and we can discuss.

**Comment by owades** [comment] 2023-01-19 23:41
_I'm getting deja vu_ 

Sounds good!

**Comment by owades** [comment] 2023-01-19 23:42
And this makes sense, I see that I was interpreting parse_success_file_count = 0 incorreclty.

**Closed** 2023-01-19 23:42 UTC

**Comment by lauriemerrell** [comment] 2023-01-19 23:53
Another deja vu is that PR review should be looking for suggestions like this 😅 But yeah, `parse_success_file_count` means *of the files that were downloaded, how many were parsed successfully*
