### ISSUE TITLE
Epic: publish GTFS-Realtime data in automated monthly reports

### ISSUE THREAD

**Issue by mcplanner-zz** [cal-itp/data-infra#269] opened 2021-08-10 22:26 UTC
As shown in this [mockup](https://docs.google.com/document/d/1-iXNdl4f2EbYayKg3e7jkTALAcNzht9yGQuyIOtPLc4/edit#heading=h.bcbigeamfk52).

**Comment by evansiroky** [comment] 2022-01-26 22:31
Duplicate of #682

**Closed by evansiroky** 2022-01-26 22:31 UTC
Labels: epic
