### ISSUE TITLE
Investigate SBMTD's Feed Discrepancy

### ISSUE THREAD

**Issue by holly-g** [cal-itp/data-infra#819] opened 2021-12-03 08:38 UTC
From Olivia: 

> I noticed some oddities with the report for SBMTD, but the issue also appears in Metabase, so it might be something a bit deeper. SBMTD’s [feed](http://sbmtd.gov/google_transit/feed.zip) does have feed_info.txt and fare_leg_rules.txt. However, both [metabase ](https://metabase.k8s.calitp.jarv.us/dashboard/26-gtfs-guidelines-specific-date?feed_name=Santa%20Barbara%20Metropolitan%20Transit%20District%20(0)&relative_date=yesterday)and their [page on the reports site](https://development-build--cal-itp-reports.netlify.app/gtfs_schedule/2021/11/293/index.html) show that they do not have these.

cc @machow

**Comment by machow** [comment] 2021-12-03 17:48
AFAICT there's a fairly gnarly issue, where when we unzip SBMTD's feed, it unzips into a directory vs pulling out the files themselves. We've run into these things before, where how a feed is zipped can affect this (e.g. what zipped the feed / how it was done, and what is unzipping)

![image](https://user-images.githubusercontent.com/2574498/144648964-c5d760d1-b4e7-47a7-a684-555d77bbfa64.png)

**Comment by lauriemerrell** [comment] 2022-03-22 20:23
I submitted a mostly-dupe of this recently: #1185

**Comment by atvaccaro** [comment] 2023-03-30 17:05
Going to close, we handle this now

**Closed by atvaccaro** 2023-03-30 17:05 UTC
Labels: project-gtfs-schedule, reports-website
