### ISSUE TITLE
Transit Provider Technology stacks

### ISSUE THREAD

**Issue by e-lo** [cal-itp/data-infra#12] opened 2020-12-15 21:39 UTC
Need in queryable/joinable form so we can ask questions like:

"What was the average grade for transit providers using vendor B compared to others in their peer group"

**Comment by hunterowens** [comment] 2021-04-05 15:48
@e-lo / I  talked about initial protype of gforms - sheet-> cleanedup read only data replica in BQ / DW?

**Comment by mcplanner** [comment] 2021-07-20 21:57
The next step on this project is getting clearly defined by me.

**Comment by mcplanner** [comment] 2021-07-21 22:35
Closing as a duplicate of #204

**Closed by mcplanner** 2021-07-21 22:35 UTC
