### ISSUE TITLE
Bug: Sage Stage routes appear in gtfs_schedule.routes when filtering for AC Transit

### ISSUE THREAD

**Issue by edasmalchi** [cal-itp/data-infra#521] opened 2021-10-18 21:08 UTC
**Describe the bug**
Sage Stage routes appear in gtfs_schedule.routes when filtering for AC Transit.

**To Reproduce**
1. Filter gtfs_schedule.routes to AC Transit (calitp_itp_id == 4)
2. Note that Sage Stage routes "Reno, Redding, Klamath Falls, Canby" appear, despite not being AC Transit routes

**Expected behavior**
AC Transit routes appearing exclusively

**Comment by lauriemerrell** [comment] 2022-01-31 22:25
As of today, I cannot reproduce this. 

This query: 
```
SELECT * 
FROM `cal-itp-data-infra.gtfs_schedule.routes`
WHERE calitp_itp_id = 4
```

Returns AC Transit and Capitol Corridor routes, but not Sage Stage. I am looking into why Capitol Corridor is appearing. @edasmalchi also suggested this may be a sub-issue of #998, although I am not totally sure since this issue is significantly earlier in the pipeline.

**Comment by lauriemerrell** [comment] 2022-01-31 22:46
Capitol Corridor issue is now being tracked in #1017 and #1018 (seems separate from this.) I will also be looking into #988 separately.

Since I can't reproduce the specific Sage Stage issue, I am going to close this now. cc @holly-g please let me know if you disagree

**Comment by lauriemerrell** [comment] 2022-02-02 16:50
Heads up @edasmalchi and @holly-g - I am reopening this issue, the Sage Stage data is still available in `gtfs_schedule_history.routes` -- it's gone from `gtfs_schedule` because that only has currently active data, but this data is still in the history. (Ran into this again while addressing related issue #1018.)

The raw underlying data is still available in, for example, `gs://gtfs-data/schedule/2021-04-15T00:00:00+00:00/4_1`. Basically Sage Stage was erroneously assigned `calitp_itp_id` 4 and `calitp_url_number` 1 for some period of time. Will need to investigate **what** period of time and copy that data to the correct location.

**Comment by atvaccaro** [comment] 2023-01-26 03:19
We no longer need to do this as the backfill was performed by labeling data with actual URLs present in status.csv files.

**Closed by atvaccaro** 2023-01-26 03:19 UTC
Labels: type: bug
