### ISSUE TITLE
agencies.yml itp_id mismatches

### ISSUE THREAD

**Issue by thekaveman** [cal-itp/data-infra#113] opened 2021-05-12 05:37 UTC
I noticed a few mismatches while comparing `agencies.yml` and the "official list" spreadsheet (there may be more):

| name | agencies.yml itp_id | official list ITP_ID |
| -------| ------------------------| ------------------- |
| Commuter Express | [3](https://github.com/cal-itp/data-infra/blob/main/airflow/data/agencies.yml#L209) | 390 |
| Emery Go-Round | [6](https://github.com/cal-itp/data-infra/blob/main/airflow/data/agencies.yml#L312) | 106 |
| Eureka Transit Service | [8](https://github.com/cal-itp/data-infra/blob/main/airflow/data/agencies.yml#L317) | 108 |

**Comment by machow** [comment] 2021-05-12 14:30
Ah, shoot--I would suggest we consider "itp_id" in the pipeline to actually be something separate (say a "feed id"). We can transform in the correct keys after loading data, but can't really go back and rewrite our extraction history (e.g. what files did we download based on the agency.yml for the day). Could put up an association table with "feed_id" and the correct itp_id?

(Thinking out loud, so feel free to push back if it's easier for us to change another way)

**Comment by e-lo** [comment] 2021-05-12 15:04
Interestingly:
- ITP_IDs 3 and 8 are not taken (although 6 is Alhambra Community Transit).
- Commuter Express is really a duplicate of DASH (ITP ID 183) and both are really LA DOT.  @hunterowens and I discussed renaming DASH and Commuter Express to ~"Los Angeles DOT Transit"...which we could make ITP_ID 3?
-

**Comment by mcplanner** [comment] 2021-05-12 15:07
I've noticed a handful that look wrong and just put off making a major
research task of it. Would this be something we should bring Mark (student
researcher) in to review?

**Comment by thekaveman** [comment] 2021-05-12 15:23
There are also quite a few duplicates, e.g. `itp_id: 1` is used for:

* el-dorado-transit
* fairfield-and-suisun-transit
* glendale-beeline
* long-beach-transit
* mammoth-lakes-transit-system
* mission-bay-tma

(Aside, also noticed `itp_id: 199.0` for menlo-park-shuttles)

**Comment by thekaveman** [comment] 2021-05-12 15:25
@machow 

> I would suggest we consider "itp_id" in the pipeline to actually be something separate (say a "feed id"). We can transform in the correct keys after loading data, but can't really go back and rewrite our extraction history (e.g. what files did we download based on the agency.yml for the day). Could put up an association table with "feed_id" and the correct itp_id?

I'm not sure I follow. What is `itp_id` used for now, if anything?

**Comment by e-lo** [comment] 2021-05-12 15:57
>There are also quite a few duplicates, e.g. itp_id: 1 is used for:
>  el-dorado-transit
> fairfield-and-suisun-transit
> glendale-beeline
> long-beach-transit
> mammoth-lakes-transit-system
> mission-bay-tma

**Comment by machow** [comment] 2021-05-12 16:52
> I'm not sure I follow. What is itp_id used for now, if anything?

itp_id, and url_number (order of url in the gtfs_schedule list) is a primary key for identifying feeds. For example, if we want to know what feed files have changed, a feed is identified using its itp_id and url_number in `agencies.yml`. If we change itp_id in `agencies.yml`, we are--in the pipeline's eyes--deleting an old feed source and adding a new one. It needs a way to know that the new itp_ids refer to the same feed source (or an alternative way of identifying data feeds).

**Comment by thekaveman** [comment] 2021-05-12 16:57
> itp_id, and url_number (order of url in the gtfs_schedule list) is a primary key for identifying feeds.

The duplicates especially seems like a pretty big problem then. If I understand correctly, does this mean our existing history is wrong and should be thrown out anyway? Like, using the list of `itp_id: 1` above as an example: after processing el-dorado-transit and moving on to fairfield-and-suisun-transit, wouldn't el-dorado-transit's history be overwritten by the duplicate `itp_id` for that run?

**Comment by machow** [comment] 2021-05-12 17:14
> Like, using the list of itp_id: 1 above as an example: after processing el-dorado-transit and moving on to fairfield-and-suisun-transit, wouldn't el-dorado-transit's history be overwritten by the duplicate itp_id for that run?

Yes.

The pipeline stores a table version of the agencies.yml it used, so if we want a GTFS report out that involves tracking file changes, we should be able to flag the duplicate itp_ids where we don't have data..! Once we have a PR with `agencies.yml` updates, I'm happy to figure out how to migrate.

**Comment by e-lo** [comment] 2021-05-12 17:32
Is there (or can/should we add) a validation step on agencies.yml to make sure the primary keys aren't duped?

**Comment by hunterowens** [comment] 2021-05-24 16:53
#117 is a nice to have but, but this is good for now!

**Closed by hunterowens** 2021-05-24 16:53 UTC

**Comment by thekaveman** [comment] 2021-05-26 16:54
This was solved in #122
