### ISSUE TITLE
Bug: duplicate/non-existent ITP IDs in GTFS Schedule Feeds Latest views

### ISSUE THREAD

**Issue by edasmalchi** [cal-itp/data-infra#988] opened 2022-01-25 18:57 UTC
**Describe the bug**
In the GTFS Schedule Feeds Latest views, there appears to be data for itp_ids that do not exist in agencies.yml. In some cases, these strange itp_ids also contain data from multiple feeds that have their own unique itp_ids as well.

Strange itp_ids I've found so far: 1, 8, 2, 3 (there may be more?)

**To Reproduce**
1. In one of the GTFS Schedule Feeds Latest views (feed info or agency are good places to start), filter by `itp_id == 1` or `itp_id == 8` or `itp_id == 2` or `itp_id == 3` ...
2. Observe that data appears for apparently multiple feeds despite these itp_ids not being present in agencies.yml

**Expected behavior**
itp_ids in these views should not span multiple unrelated feeds, and should be present in agencies.yml

**Additional context**
For example, filtering by `itp_id == 1` gives data for Long Beach Transit alongside Eastern Sierra Transit Authority and Fairfield and Suisun Transit, despite these feeds not being related and having their own itp_ids (170, 99, and 110)...

**Comment by lauriemerrell** [comment] 2022-01-31 22:22
Wondering if this is related to #521

**Comment by lauriemerrell** [comment] 2022-04-01 13:27
Some of this is caused by #235 (duplicate), but I think that there is at least some aspect of another issue here that's akin to #1184 (like, there are two things here:

1. The logic in these `gtfs_schedule` tables should have filtered out stuff that's not marked as current
2. But separately, the things that aren't current should have been marked as deleted in some more obvious way)

**Comment by lauriemerrell** [comment] 2022-04-07 21:32
@edasmalchi I am closing this as fixed by #1320 since `GTFS Schedule Feeds Latest` itself is ok now. But I am moving the second issue (the fact that the mislabeled data exists at all) to #1353 for subsequent remediation.

**Closed by lauriemerrell** 2022-04-07 21:32 UTC
Labels: type: bug, project-gtfs-schedule
